### ISSUE TITLE
SyntaxError: Unexpected token } in bin/load-gedcom

### ISSUE THREAD

**Issue by mstenta** [woodbri/family-tree-nodejs#2]
I tried loading my gedcom file, but received an error:

```
$ bin/load-gedcom < mstenta.ged
/home/mstenta/Docker/experimental/family-tree-nodejs/bin/load-gedcom:934
        };
        ^

SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Also, I had to change the ownership of bin/load-gedcom to be executable.

**Comment by mstenta** [comment]
Oh maybe this is because I'm running load-gedcom on my host, which has a VERY old version of Node.js?

I will try running it with Docker instead...

**Comment by mstenta** [comment]
Hmm, nope - same error.

**Comment by mstenta** [comment]
For future reference, this is how I ran it in Docker:

`sudo docker run --rm -v ${PWD}:/app node:latest /app/bin/load-gedcom < mstenta.ged`

**Comment by woodbri** [comment]
I just ran into this myself, and pushed a fix for it. Closing.
